[package]
name = "poof-player"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.11", features = ["client", "gateway", "voice"] }
songbird = "0.4"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"

