[package]
name = "poof-player"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.11.7", default-features = false, features = ["client", "gateway", "voice", "rustls_backend", "http"] }

songbird = "0.4"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"

